# latexmk configuration for memoria.tex
# Adds makeglossaries to the build chain so the Lista de Acrónimos
# is regenerated automatically whenever an acronym is added or modified.

$pdf_mode = 1;
$pdflatex = 'pdflatex --shell-escape -interaction=nonstopmode -synctex=1 -file-line-error %O %S';

# Acronym list: .acn (generated by pdflatex) -> .acr (consumed by pdflatex)
add_cus_dep('acn', 'acr', 0, 'makeglossaries');
# Main glossary: .glo -> .gls
add_cus_dep('glo', 'gls', 0, 'makeglossaries');

sub makeglossaries {
    my ($name, $path) = fileparse($_[0]);
    pushd $path;
    my $code = system "makeglossaries \"$name\"";
    popd;
    return $code;
}
