This is makeindex, version 2.16 [MiKTeX 25.12].
Scanning style file ./memoria.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file memoria.acn....done (65 entries accepted, 0 rejected).
Sorting entries....done (460 comparisons).
Generating output file memoria.acr....done (123 lines written, 0 warnings).
Output written in memoria.acr.
Transcript written in memoria.alg.
